name: BE Code Formatter

on:
  pull_request:
  push:
  
jobs:
  clang-format:
    name: "Clang Formatter"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout ${{ github.ref }} ( ${{ github.sha }} )"
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          submodules: recursive

      - name: build fe
        run: |
          sudo apt-get install -y byacc
          bash ./build.sh --fe --clean
        
      - name: "Format it!"
        uses: DoozyX/clang-format-lint-action@master
        id: be_clang_format
        with:
          source: 'be/src be/test'
          clangFormatVersion: 14
          inplace: False
          
#          inplace: True
#      - uses: EndBug/add-and-commit@v4
#        with:
#          committer_name: dulong41
#          committer_email: dulong@starrrocks.com
#          message: 'Committing clang-format changes'
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
