name: label

on:
  pull_request_target:
    branches:
      - main
      - branch-2.2
      - branch-2.3
      - branch-2.4
      - branch-2.5
    types:
      - opened
      - reopened
      - edited

jobs:
  modify-branch-label:
    runs-on: ubuntu-latest
    if: >
      (startsWith(github.event.pull_request.title, '[BugFix]') ||
       startsWith(github.event.pull_request.title, '[Enhancement]'))&&
      !contains(github.event.pull_request.title, 'cherry-pick') &&
      !contains(github.event.pull_request.title, 'backport')
    steps:
      - name: add branch-2.5 label
        if: contains(toJson(github.event.pull_request.body), '[x] 2.5')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: 2.5

      - name: add branch-2.4 label
        if: contains(toJson(github.event.pull_request.body), '[x] 2.4')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: 2.4

      - name: add branch-2.3 label
        if: contains(toJson(github.event.pull_request.body), '[x] 2.3')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: 2.3

      - name: add branch-2.2 label
        if: contains(toJson(github.event.pull_request.body), '[x] 2.2')
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: 2.2

      - name: remove branch-2.5 label
        if: contains(toJson(github.event.pull_request.body), '[ ] 2.5')
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: 2.5

      - name: remove branch-2.4 label
        if: contains(toJson(github.event.pull_request.body), '[ ] 2.4')
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: 2.4

      - name: remove branch-2.3 label
        if: contains(toJson(github.event.pull_request.body), '[ ] 2.3')
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: 2.3

      - name: remove branch-2.2 label
        if: contains(toJson(github.event.pull_request.body), '[ ] 2.2')
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: 2.2

      - name: check-done
        if: >
          (startsWith(github.event.pull_request.title, '[BugFix]') ||
           startsWith(github.event.pull_request.title, '[Enhancement]'))&&
          !contains(github.event.pull_request.title, 'cherry-pick') &&
          !contains(github.event.pull_request.title, 'backport') &&
          contains(toJson(github.event.pull_request.body), '[ ] I have checked the version labels')
        run: |
          echo "You must mark this checkbox - I have checked the version labels which the pr will be auto backported to target branch"
          exit 1

